### ISSUE TITLE
jobs in status "waiting" and empty log

### ISSUE THREAD

**Issue by sophiasw** [chaimeleon-eu/jobman#12]
Jobs I started a week ago are still in status "waiting". As the logs are empty, I wouldn't know how to debug this.

**Comment by Palollo** [comment]
This is important, because sometimes there is an error which cause the status will be "waiting" forever. For example, if the user simply writes a bad image name, Kubernetes will try to download the wrong image all the time without success.
Now jobman prints only the status of `job` which is "waiting/pending" in this case, I suggest to add the status of the `Pod` to let the user know more details of what is happening.

**Comment by asalic** [comment]
solved in 1.3.14-BETA, should now show the majority of problems when launcghing the pods in the output of the logs command
